name: delivery_management
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Package Support Call API
  http: ^1.2.1

  # Package Support Icon
  cupertino_icons: ^1.0.6

  # Package Support Status Management
  flutter_bloc: ^8.1.4

  # Package Support Notification

  # Package Support 
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  dropdown_button2: ^2.3.9
  awesome_notifications: ^0.9.3+1
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
